version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - ndlabs

  kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: binance-trading-pairs:1:1
      networks:
        - ndlabs

  kafka-ui:
      image: provectuslabs/kafka-ui:latest
      depends_on:
        - kafka
      ports:
        - 8090:8080
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      networks:
        - ndlabs
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ndlabs
  app:
    build: .
    image: app:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
    environment:
      APP_KAFKA_BOOSTRAP_SERVER: kafka:9092
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_POST: 6379
    networks:
      - ndlabs
networks:
  ndlabs:
    driver: bridge